<?xml version="1.0" encoding="utf-8"?><Database Name="VBBDB" Class="VBBDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\VBBDB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="VBB.Properties.Settings" SettingsPropertyName="VBBDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="PostNo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostText" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="LastDonationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="RequestText" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
</Database>